name: Deploy to DigitalOcean

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. GitHub tự tải code về máy ảo của nó
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Copy toàn bộ code từ GitHub sang Server (Dùng SCP)
    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        source: "."
        target: "/root/optibot"
        rm: true # Xóa code cũ trước khi copy code mới

    # 3. Vào Server để Build Docker (Lúc này code đã có sẵn rồi)
    - name: Build Docker Image via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          cd /root/optibot
          
          # Build lại Image
          docker build -t optibot:v1 .
          
          # Xoa Image rac (dọn dẹp)
          docker image prune -f
          
          echo "✅ DONE! Code updated and Image built."